In [7]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
import os
import sys

In [6]:
df = pd.read_excel('Telco_customer_churn.xlsx')
print(df.head())

   CustomerID  Count        Country       State         City  Zip Code  \
0  3668-QPYBK      1  United States  California  Los Angeles     90003
1  9237-HQITU      1  United States  California  Los Angeles     90005
2  9305-CDSKC      1  United States  California  Los Angeles     90006
3  7892-POOKP      1  United States  California  Los Angeles     90010
4  0280-XJGEX      1  United States  California  Los Angeles     90015

                 Lat Long   Latitude   Longitude  Gender  ...        Contract  \
0  33.964131, -118.272783  33.964131 -118.272783    Male  ...  Month-to-month
1   34.059281, -118.30742  34.059281 -118.307420  Female  ...  Month-to-month
2  34.048013, -118.293953  34.048013 -118.293953  Female  ...  Month-to-month
3  34.062125, -118.315709  34.062125 -118.315709  Female  ...  Month-to-month
4  34.039224, -118.266293  34.039224 -118.266293    Male  ...  Month-to-month

  Paperless Billing             Payment Method  Monthly Charges Total Charges  \
0               Yes               Mailed check            53.85        108.15
1               Yes           Electronic check            70.70        151.65
2               Yes           Electronic check            99.65         820.5
3               Yes           Electronic check           104.80       3046.05
4               Yes  Bank transfer (automatic)           103.70        5036.3

  Churn Label Churn Value Churn Score  CLTV                   Churn Reason
0         Yes           1          86  3239   Competitor made better offer
1         Yes           1          67  2701                          Moved
2         Yes           1          86  5372                          Moved
3         Yes           1          84  5003                          Moved
4         Yes           1          89  5340  Competitor had better devices

[5 rows x 33 columns]

In [8]:
df.shape

(7043, 33)

In [9]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), object(1), str(23)
memory usage: 1.8+ MB
None

In [10]:
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='str')

In [11]:
df.nunique()

CustomerID           7043
Count                   1
Country                 1
State                   1
City                 1129
Zip Code             1652
Lat Long             1652
Latitude             1652
Longitude            1651
Gender                  2
Senior Citizen          2
Partner                 2
Dependents              2
Tenure Months          73
Phone Service           2
Multiple Lines          3
Internet Service        3
Online Security         3
Online Backup           3
Device Protection       3
Tech Support            3
Streaming TV            3
Streaming Movies        3
Contract                3
Paperless Billing       2
Payment Method          4
Monthly Charges      1585
Total Charges        6531
Churn Label             2
Churn Value             2
Churn Score            85
CLTV                 3438
Churn Reason           20
dtype: int64

In [13]:
df['Churn Value'].value_counts()

Churn Value
0    5174
1    1869
Name: count, dtype: int64

In [14]:
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [15]:
df.shape

(7043, 33)

In [16]:
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='str')

In [17]:
df['Churn Value'].value_counts()

Churn Value
0    5174
1    1869
Name: count, dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [20]:
#columns name in lower case and replace space with underscore
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [21]:
df.columns

Index(['customerid', 'count', 'country', 'state', 'city', 'zip_code',
       'lat_long', 'latitude', 'longitude', 'gender', 'senior_citizen',
       'partner', 'dependents', 'tenure_months', 'phone_service',
       'multiple_lines', 'internet_service', 'online_security',
       'online_backup', 'device_protection', 'tech_support', 'streaming_tv',
       'streaming_movies', 'contract', 'paperless_billing', 'payment_method',
       'monthly_charges', 'total_charges', 'churn_label', 'churn_value',
       'churn_score', 'cltv', 'churn_reason'],
      dtype='str')

In [31]:
#create bins
tenure_labels = ['0-1 years ', '1-2 years', '2-4 years' , '4+ years']
df['tenure_group'] = pd.cut(df['tenure_months'], bins=4, labels=tenure_labels)

In [36]:
#create monthly charges segment
monthly_charges_groups = [ 'Low', 'Medium', 'High']
df['monthly_charges_segment'] = pd.qcut(df['monthly_charges'], q=3, labels=monthly_charges_groups)

In [38]:
df[['tenure_months', 'tenure_group']].head(5)

   tenure_months tenure_group
0              2   0-1 years
1              2   0-1 years
2              8   0-1 years
3             28    1-2 years
4             49    2-4 years

In [39]:
df[['monthly_charges', 'monthly_charges_segment']].head(5)

   monthly_charges monthly_charges_segment
0            53.85                  Medium
1            70.70                  Medium
2            99.65                    High
3           104.80                    High
4           103.70                    High

In [ ]:
# TO SAVE THE CLEANED DATASET
df.to_excel('Telco_customer_churn_cleaned.xlsx', index=False)

In [41]:
#code for check where save dataset is saved
print(os.getcwd())

c:\MyProjects\Customer_Churn_Project

In [42]:
from sqlalchemy import create_engine

#step 1: connect to MySQL database
username = 'root'
password = 'satendra349'  
host = 'localhost' 
port = '3306'
database_name = 'customer_churn' 

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database_name}')

#step 2: write the DataFrame to MySQL database
table_name = 'customer'
df.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"DataFrame has been written to MySQL table '{table_name}' in database '{database_name}'.")

DataFrame has been written to MySQL table 'customer' in database 'customer_churn'.

In [45]:
# read the data back from MySQL to verify
query = f'SELECT * FROM {table_name} LIMIT 5;'
result_df = pd.read_sql(query, con=engine)
print(result_df)

   customerid  count        country       state         city  zip_code  \
0  3668-QPYBK      1  United States  California  Los Angeles     90003
1  9237-HQITU      1  United States  California  Los Angeles     90005
2  9305-CDSKC      1  United States  California  Los Angeles     90006
3  7892-POOKP      1  United States  California  Los Angeles     90010
4  0280-XJGEX      1  United States  California  Los Angeles     90015

                 lat_long   latitude   longitude  gender  ...  \
0  33.964131, -118.272783  33.964131 -118.272783    Male  ...
1   34.059281, -118.30742  34.059281 -118.307420  Female  ...
2  34.048013, -118.293953  34.048013 -118.293953  Female  ...
3  34.062125, -118.315709  34.062125 -118.315709  Female  ...
4  34.039224, -118.266293  34.039224 -118.266293    Male  ...

              payment_method monthly_charges total_charges  churn_label  \
0               Mailed check           53.85        108.15          Yes
1           Electronic check           70.70        151.65          Yes
2           Electronic check           99.65         820.5          Yes
3           Electronic check          104.80       3046.05          Yes
4  Bank transfer (automatic)          103.70        5036.3          Yes

  churn_value churn_score  cltv                   churn_reason tenure_group  \
0           1          86  3239   Competitor made better offer   0-1 years
1           1          67  2701                          Moved   0-1 years
2           1          86  5372                          Moved   0-1 years
3           1          84  5003                          Moved    1-2 years
4           1          89  5340  Competitor had better devices    2-4 years

  monthly_charges_segment
0                  Medium
1                  Medium
2                    High
3                    High
4                    High

[5 rows x 35 columns]

In [47]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:satendra349@localhost:3306/customer_behavior"
)

print("Connected Successfully")

Connected Successfully

In [8]:
df = pd.read_excel('Telco_customer_churn_cleaned.xlsx')
print(df.head())

   customerid  count        country       state         city  zip_code  \
0  3668-QPYBK      1  United States  California  Los Angeles     90003
1  9237-HQITU      1  United States  California  Los Angeles     90005
2  9305-CDSKC      1  United States  California  Los Angeles     90006
3  7892-POOKP      1  United States  California  Los Angeles     90010
4  0280-XJGEX      1  United States  California  Los Angeles     90015

                 lat_long   latitude   longitude  gender  ...  \
0  33.964131, -118.272783  33.964131 -118.272783    Male  ...
1   34.059281, -118.30742  34.059281 -118.307420  Female  ...
2  34.048013, -118.293953  34.048013 -118.293953  Female  ...
3  34.062125, -118.315709  34.062125 -118.315709  Female  ...
4  34.039224, -118.266293  34.039224 -118.266293    Male  ...

              payment_method monthly_charges total_charges  churn_label  \
0               Mailed check           53.85        108.15          Yes
1           Electronic check           70.70        151.65          Yes
2           Electronic check           99.65        820.50          Yes
3           Electronic check          104.80       3046.05          Yes
4  Bank transfer (automatic)          103.70       5036.30          Yes

  churn_value churn_score  cltv                   churn_reason tenure_group  \
0           1          86  3239   Competitor made better offer   0-1 years
1           1          67  2701                          Moved   0-1 years
2           1          86  5372                          Moved   0-1 years
3           1          84  5003                          Moved    1-2 years
4           1          89  5340  Competitor had better devices    2-4 years

  monthly_charges_segment
0                  Medium
1                  Medium
2                    High
3                    High
4                    High

[5 rows x 35 columns]

In [9]:
df.columns

Index(['customerid', 'count', 'country', 'state', 'city', 'zip_code',
       'lat_long', 'latitude', 'longitude', 'gender', 'senior_citizen',
       'partner', 'dependents', 'tenure_months', 'phone_service',
       'multiple_lines', 'internet_service', 'online_security',
       'online_backup', 'device_protection', 'tech_support', 'streaming_tv',
       'streaming_movies', 'contract', 'paperless_billing', 'payment_method',
       'monthly_charges', 'total_charges', 'churn_label', 'churn_value',
       'churn_score', 'cltv', 'churn_reason', 'tenure_group',
       'monthly_charges_segment'],
      dtype='str')